/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.28                          *
*        Compiled Jan 30 2015, 16:41:06                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END
#include <rtthread.h>
#ifdef RT_USING_STEMWIN
#if 1
#include "DIALOG.h"
#include <drv_ADC.h>

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_FRAMEWIN_0 (GUI_ID_USER + 0x00)
#define ID_GRAPH_0 (GUI_ID_USER + 0x02)
#define ID_BUTTON_0 (GUI_ID_USER + 0x02)


// USER START (Optionally insert additional defines)
I16 p = 1;
GRAPH_DATA_Handle hGraph;

// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { FRAMEWIN_CreateIndirect, "Motor state", ID_FRAMEWIN_0, 0, 0, 800, 480, 0, 0x0, 0 },
  { GRAPH_CreateIndirect, "Graph", ID_GRAPH_0, 0, 0, 800,360, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_0, 360, 380, 80, 20, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/
#if 0
void updateGraph(void)
{
	int16_t i;
	i = Global_User_ADC.PhaseB.qV_value*360/0xfff;
    GRAPH_DATA_YT_AddValue(hGraph ,i);
    //WM_InvalidateWindow(pMsg->hWin);
}
#endif
#if 1
// USER START (Optionally insert additional static code)
static void _cbCpuWindow(WM_MESSAGE * pMsg) {
 
  WM_HTIMER hTimer;
  static int16_t i;
  switch (pMsg->MsgId) 
  {
  case WM_CREATE:
    /* Create timer */
	hTimer = WM_CreateTimer(pMsg->hWin, 0, 1, 0);
    break;
    
  case WM_TIMER:
  	i = Global_User_ADC.PhaseB.qV_value*360/0xfff;
    GRAPH_DATA_YT_AddValue(hGraph ,i);
    WM_InvalidateWindow(pMsg->hWin);
	WM_RestartTimer(pMsg->Data.v, 1);
    break; 
    
  case WM_DELETE:
    WM_DeleteTimer(hTimer);
    break;
    
  default:
    WM_DefaultProc(pMsg);
  }
}
#endif
// USER END

/*********************************************************************
*
*       _cbDialog
*/
	


static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  // USER END
  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Graph'
    //
    #if 1
	WM_CreateWindowAsChild(0, 0, 800, 360, pMsg->hWin, WM_CF_SHOW | WM_CF_HASTRANS, _cbCpuWindow , 0); 
	#endif
    hItem = WM_GetDialogItem(pMsg->hWin, ID_GRAPH_0);
    GRAPH_SetBorder(hItem, 2, 2, 2, 2);
	GRAPH_SetColor(hItem, GUI_YELLOW,GRAPH_CI_GRID);
	GRAPH_SetGridDistX(hItem,40);
	GRAPH_SetGridDistY(hItem,40);
	GRAPH_SetLineStyleH(hItem,GUI_LS_DOT);
	GRAPH_SetLineStyleV(hItem,GUI_LS_DOT);
	GRAPH_SetGridVis(hItem,1);
	hGraph = GRAPH_DATA_YT_Create(GUI_RED,800,&p,1);
	GRAPH_AttachData(hItem,hGraph);
	GRAPH_DATA_YT_MirrorX(hGraph,0);
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
   case WM_NOTIFY_PARENT:
	Id    = WM_GetId(pMsg->hWinSrc);
	NCode = pMsg->Data.v;
	switch(Id) {
	case ID_BUTTON_0: // Notifications sent by 'Button'
	switch(NCode) {
	case WM_NOTIFICATION_CLICKED:
	// USER START (Optionally insert code for reacting on notification message)
	// USER END
	break;
	case WM_NOTIFICATION_RELEASED:
	// USER START (Optionally insert code for reacting on notification message)
	// USER END
	break;
	// USER START (Optionally insert additional code for further notification handling)
	// USER END
	}
	break;
	// USER START (Optionally insert additional code for further Ids)
	// USER END
	}
	break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateFramewin
*/
WM_HWIN CreateFramewin(void);
WM_HWIN CreateFramewin(void) {
  WM_HWIN hWin;
  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}
#endif
#endif
// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
