import rtconfig
Import('RTT_ROOT')
from building import *

# get current directory
cwd = GetCurrentDir()

# The set of source files associated with this SConscript file.

src = Glob('*.c')

path = [cwd ]

CPPDEFINES = ['']
group = DefineGroup('J1939', src, depend = ['RT_USING_J1939'], CPPPATH = path, CPPDEFINES = CPPDEFINES)

Return('group')
