// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.2
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xctrl_docurrentctrl.h"
#include "xctrl_usr_docurrentctrl.h"

extern XCtrl_docurrentctrl_Config XCtrl_docurrentctrl_ConfigTable[];

XCtrl_docurrentctrl_Config *XCtrl_docurrentctrl_LookupConfig(u16 DeviceId) {
	XCtrl_docurrentctrl_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XCTRL_DOCURRENTCTRL_NUM_INSTANCES; Index++) {
		if (XCtrl_docurrentctrl_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XCtrl_docurrentctrl_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XCtrl_docurrentctrl_Initialize(XCtrl_docurrentctrl *InstancePtr, u16 DeviceId) {
	XCtrl_docurrentctrl_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XCtrl_docurrentctrl_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XCtrl_docurrentctrl_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

