// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.2
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xctrl_docurrentctrl.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XCtrl_docurrentctrl_CfgInitialize(XCtrl_docurrentctrl *InstancePtr, XCtrl_docurrentctrl_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Busa_BaseAddress = ConfigPtr->Busa_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XCtrl_docurrentctrl_Start(XCtrl_docurrentctrl *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCtrl_docurrentctrl_ReadReg(InstancePtr->Busa_BaseAddress, XCTRL_DOCURRENTCTRL_BUSA_ADDR_AP_CTRL) & 0x80;
    XCtrl_docurrentctrl_WriteReg(InstancePtr->Busa_BaseAddress, XCTRL_DOCURRENTCTRL_BUSA_ADDR_AP_CTRL, Data | 0x01);
}

u32 XCtrl_docurrentctrl_IsDone(XCtrl_docurrentctrl *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCtrl_docurrentctrl_ReadReg(InstancePtr->Busa_BaseAddress, XCTRL_DOCURRENTCTRL_BUSA_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XCtrl_docurrentctrl_IsIdle(XCtrl_docurrentctrl *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCtrl_docurrentctrl_ReadReg(InstancePtr->Busa_BaseAddress, XCTRL_DOCURRENTCTRL_BUSA_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XCtrl_docurrentctrl_IsReady(XCtrl_docurrentctrl *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCtrl_docurrentctrl_ReadReg(InstancePtr->Busa_BaseAddress, XCTRL_DOCURRENTCTRL_BUSA_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XCtrl_docurrentctrl_EnableAutoRestart(XCtrl_docurrentctrl *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCtrl_docurrentctrl_WriteReg(InstancePtr->Busa_BaseAddress, XCTRL_DOCURRENTCTRL_BUSA_ADDR_AP_CTRL, 0x80);
}

void XCtrl_docurrentctrl_DisableAutoRestart(XCtrl_docurrentctrl *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCtrl_docurrentctrl_WriteReg(InstancePtr->Busa_BaseAddress, XCTRL_DOCURRENTCTRL_BUSA_ADDR_AP_CTRL, 0);
}

void XCtrl_docurrentctrl_Set_in_f_iqref(XCtrl_docurrentctrl *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCtrl_docurrentctrl_WriteReg(InstancePtr->Busa_BaseAddress, XCTRL_DOCURRENTCTRL_BUSA_ADDR_IN_F_IQREF_DATA, Data);
}

u32 XCtrl_docurrentctrl_Get_in_f_iqref(XCtrl_docurrentctrl *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCtrl_docurrentctrl_ReadReg(InstancePtr->Busa_BaseAddress, XCTRL_DOCURRENTCTRL_BUSA_ADDR_IN_F_IQREF_DATA);
    return Data;
}

void XCtrl_docurrentctrl_Set_in_f_idref(XCtrl_docurrentctrl *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCtrl_docurrentctrl_WriteReg(InstancePtr->Busa_BaseAddress, XCTRL_DOCURRENTCTRL_BUSA_ADDR_IN_F_IDREF_DATA, Data);
}

u32 XCtrl_docurrentctrl_Get_in_f_idref(XCtrl_docurrentctrl *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCtrl_docurrentctrl_ReadReg(InstancePtr->Busa_BaseAddress, XCTRL_DOCURRENTCTRL_BUSA_ADDR_IN_F_IDREF_DATA);
    return Data;
}

void XCtrl_docurrentctrl_Set_in_f_udc(XCtrl_docurrentctrl *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCtrl_docurrentctrl_WriteReg(InstancePtr->Busa_BaseAddress, XCTRL_DOCURRENTCTRL_BUSA_ADDR_IN_F_UDC_DATA, Data);
}

u32 XCtrl_docurrentctrl_Get_in_f_udc(XCtrl_docurrentctrl *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCtrl_docurrentctrl_ReadReg(InstancePtr->Busa_BaseAddress, XCTRL_DOCURRENTCTRL_BUSA_ADDR_IN_F_UDC_DATA);
    return Data;
}

void XCtrl_docurrentctrl_Set_in_f_ttop(XCtrl_docurrentctrl *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCtrl_docurrentctrl_WriteReg(InstancePtr->Busa_BaseAddress, XCTRL_DOCURRENTCTRL_BUSA_ADDR_IN_F_TTOP_DATA, Data);
}

u32 XCtrl_docurrentctrl_Get_in_f_ttop(XCtrl_docurrentctrl *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCtrl_docurrentctrl_ReadReg(InstancePtr->Busa_BaseAddress, XCTRL_DOCURRENTCTRL_BUSA_ADDR_IN_F_TTOP_DATA);
    return Data;
}

void XCtrl_docurrentctrl_Set_in_f_ia(XCtrl_docurrentctrl *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCtrl_docurrentctrl_WriteReg(InstancePtr->Busa_BaseAddress, XCTRL_DOCURRENTCTRL_BUSA_ADDR_IN_F_IA_DATA, Data);
}

u32 XCtrl_docurrentctrl_Get_in_f_ia(XCtrl_docurrentctrl *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCtrl_docurrentctrl_ReadReg(InstancePtr->Busa_BaseAddress, XCTRL_DOCURRENTCTRL_BUSA_ADDR_IN_F_IA_DATA);
    return Data;
}

void XCtrl_docurrentctrl_Set_in_f_ib(XCtrl_docurrentctrl *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCtrl_docurrentctrl_WriteReg(InstancePtr->Busa_BaseAddress, XCTRL_DOCURRENTCTRL_BUSA_ADDR_IN_F_IB_DATA, Data);
}

u32 XCtrl_docurrentctrl_Get_in_f_ib(XCtrl_docurrentctrl *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCtrl_docurrentctrl_ReadReg(InstancePtr->Busa_BaseAddress, XCTRL_DOCURRENTCTRL_BUSA_ADDR_IN_F_IB_DATA);
    return Data;
}

void XCtrl_docurrentctrl_Set_in_f_ic(XCtrl_docurrentctrl *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCtrl_docurrentctrl_WriteReg(InstancePtr->Busa_BaseAddress, XCTRL_DOCURRENTCTRL_BUSA_ADDR_IN_F_IC_DATA, Data);
}

u32 XCtrl_docurrentctrl_Get_in_f_ic(XCtrl_docurrentctrl *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCtrl_docurrentctrl_ReadReg(InstancePtr->Busa_BaseAddress, XCTRL_DOCURRENTCTRL_BUSA_ADDR_IN_F_IC_DATA);
    return Data;
}

void XCtrl_docurrentctrl_Set_in_f_theta(XCtrl_docurrentctrl *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCtrl_docurrentctrl_WriteReg(InstancePtr->Busa_BaseAddress, XCTRL_DOCURRENTCTRL_BUSA_ADDR_IN_F_THETA_DATA, Data);
}

u32 XCtrl_docurrentctrl_Get_in_f_theta(XCtrl_docurrentctrl *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCtrl_docurrentctrl_ReadReg(InstancePtr->Busa_BaseAddress, XCTRL_DOCURRENTCTRL_BUSA_ADDR_IN_F_THETA_DATA);
    return Data;
}

void XCtrl_docurrentctrl_Set_in_f_kp_id(XCtrl_docurrentctrl *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCtrl_docurrentctrl_WriteReg(InstancePtr->Busa_BaseAddress, XCTRL_DOCURRENTCTRL_BUSA_ADDR_IN_F_KP_ID_DATA, Data);
}

u32 XCtrl_docurrentctrl_Get_in_f_kp_id(XCtrl_docurrentctrl *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCtrl_docurrentctrl_ReadReg(InstancePtr->Busa_BaseAddress, XCTRL_DOCURRENTCTRL_BUSA_ADDR_IN_F_KP_ID_DATA);
    return Data;
}

void XCtrl_docurrentctrl_Set_in_f_ki_id(XCtrl_docurrentctrl *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCtrl_docurrentctrl_WriteReg(InstancePtr->Busa_BaseAddress, XCTRL_DOCURRENTCTRL_BUSA_ADDR_IN_F_KI_ID_DATA, Data);
}

u32 XCtrl_docurrentctrl_Get_in_f_ki_id(XCtrl_docurrentctrl *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCtrl_docurrentctrl_ReadReg(InstancePtr->Busa_BaseAddress, XCTRL_DOCURRENTCTRL_BUSA_ADDR_IN_F_KI_ID_DATA);
    return Data;
}

void XCtrl_docurrentctrl_Set_in_f_id_pidmax(XCtrl_docurrentctrl *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCtrl_docurrentctrl_WriteReg(InstancePtr->Busa_BaseAddress, XCTRL_DOCURRENTCTRL_BUSA_ADDR_IN_F_ID_PIDMAX_DATA, Data);
}

u32 XCtrl_docurrentctrl_Get_in_f_id_pidmax(XCtrl_docurrentctrl *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCtrl_docurrentctrl_ReadReg(InstancePtr->Busa_BaseAddress, XCTRL_DOCURRENTCTRL_BUSA_ADDR_IN_F_ID_PIDMAX_DATA);
    return Data;
}

void XCtrl_docurrentctrl_Set_in_f_id_pidmin(XCtrl_docurrentctrl *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCtrl_docurrentctrl_WriteReg(InstancePtr->Busa_BaseAddress, XCTRL_DOCURRENTCTRL_BUSA_ADDR_IN_F_ID_PIDMIN_DATA, Data);
}

u32 XCtrl_docurrentctrl_Get_in_f_id_pidmin(XCtrl_docurrentctrl *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCtrl_docurrentctrl_ReadReg(InstancePtr->Busa_BaseAddress, XCTRL_DOCURRENTCTRL_BUSA_ADDR_IN_F_ID_PIDMIN_DATA);
    return Data;
}

void XCtrl_docurrentctrl_Set_in_f_kp_iq(XCtrl_docurrentctrl *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCtrl_docurrentctrl_WriteReg(InstancePtr->Busa_BaseAddress, XCTRL_DOCURRENTCTRL_BUSA_ADDR_IN_F_KP_IQ_DATA, Data);
}

u32 XCtrl_docurrentctrl_Get_in_f_kp_iq(XCtrl_docurrentctrl *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCtrl_docurrentctrl_ReadReg(InstancePtr->Busa_BaseAddress, XCTRL_DOCURRENTCTRL_BUSA_ADDR_IN_F_KP_IQ_DATA);
    return Data;
}

void XCtrl_docurrentctrl_Set_in_f_ki_iq(XCtrl_docurrentctrl *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCtrl_docurrentctrl_WriteReg(InstancePtr->Busa_BaseAddress, XCTRL_DOCURRENTCTRL_BUSA_ADDR_IN_F_KI_IQ_DATA, Data);
}

u32 XCtrl_docurrentctrl_Get_in_f_ki_iq(XCtrl_docurrentctrl *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCtrl_docurrentctrl_ReadReg(InstancePtr->Busa_BaseAddress, XCTRL_DOCURRENTCTRL_BUSA_ADDR_IN_F_KI_IQ_DATA);
    return Data;
}

void XCtrl_docurrentctrl_Set_in_f_iq_pidmax(XCtrl_docurrentctrl *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCtrl_docurrentctrl_WriteReg(InstancePtr->Busa_BaseAddress, XCTRL_DOCURRENTCTRL_BUSA_ADDR_IN_F_IQ_PIDMAX_DATA, Data);
}

u32 XCtrl_docurrentctrl_Get_in_f_iq_pidmax(XCtrl_docurrentctrl *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCtrl_docurrentctrl_ReadReg(InstancePtr->Busa_BaseAddress, XCTRL_DOCURRENTCTRL_BUSA_ADDR_IN_F_IQ_PIDMAX_DATA);
    return Data;
}

void XCtrl_docurrentctrl_Set_in_f_iq_pidmin(XCtrl_docurrentctrl *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCtrl_docurrentctrl_WriteReg(InstancePtr->Busa_BaseAddress, XCTRL_DOCURRENTCTRL_BUSA_ADDR_IN_F_IQ_PIDMIN_DATA, Data);
}

u32 XCtrl_docurrentctrl_Get_in_f_iq_pidmin(XCtrl_docurrentctrl *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCtrl_docurrentctrl_ReadReg(InstancePtr->Busa_BaseAddress, XCTRL_DOCURRENTCTRL_BUSA_ADDR_IN_F_IQ_PIDMIN_DATA);
    return Data;
}

void XCtrl_docurrentctrl_Set_in_f_ud(XCtrl_docurrentctrl *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCtrl_docurrentctrl_WriteReg(InstancePtr->Busa_BaseAddress, XCTRL_DOCURRENTCTRL_BUSA_ADDR_IN_F_UD_DATA, Data);
}

u32 XCtrl_docurrentctrl_Get_in_f_ud(XCtrl_docurrentctrl *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCtrl_docurrentctrl_ReadReg(InstancePtr->Busa_BaseAddress, XCTRL_DOCURRENTCTRL_BUSA_ADDR_IN_F_UD_DATA);
    return Data;
}

void XCtrl_docurrentctrl_Set_in_f_uq(XCtrl_docurrentctrl *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCtrl_docurrentctrl_WriteReg(InstancePtr->Busa_BaseAddress, XCTRL_DOCURRENTCTRL_BUSA_ADDR_IN_F_UQ_DATA, Data);
}

u32 XCtrl_docurrentctrl_Get_in_f_uq(XCtrl_docurrentctrl *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCtrl_docurrentctrl_ReadReg(InstancePtr->Busa_BaseAddress, XCTRL_DOCURRENTCTRL_BUSA_ADDR_IN_F_UQ_DATA);
    return Data;
}

void XCtrl_docurrentctrl_Set_in_f_mod(XCtrl_docurrentctrl *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCtrl_docurrentctrl_WriteReg(InstancePtr->Busa_BaseAddress, XCTRL_DOCURRENTCTRL_BUSA_ADDR_IN_F_MOD_DATA, Data);
}

u32 XCtrl_docurrentctrl_Get_in_f_mod(XCtrl_docurrentctrl *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCtrl_docurrentctrl_ReadReg(InstancePtr->Busa_BaseAddress, XCTRL_DOCURRENTCTRL_BUSA_ADDR_IN_F_MOD_DATA);
    return Data;
}

u32 XCtrl_docurrentctrl_Get_t_f_ta(XCtrl_docurrentctrl *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCtrl_docurrentctrl_ReadReg(InstancePtr->Busa_BaseAddress, XCTRL_DOCURRENTCTRL_BUSA_ADDR_T_F_TA_DATA);
    return Data;
}

u32 XCtrl_docurrentctrl_Get_t_f_ta_vld(XCtrl_docurrentctrl *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCtrl_docurrentctrl_ReadReg(InstancePtr->Busa_BaseAddress, XCTRL_DOCURRENTCTRL_BUSA_ADDR_T_F_TA_CTRL);
    return Data & 0x1;
}

u32 XCtrl_docurrentctrl_Get_t_f_tb(XCtrl_docurrentctrl *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCtrl_docurrentctrl_ReadReg(InstancePtr->Busa_BaseAddress, XCTRL_DOCURRENTCTRL_BUSA_ADDR_T_F_TB_DATA);
    return Data;
}

u32 XCtrl_docurrentctrl_Get_t_f_tb_vld(XCtrl_docurrentctrl *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCtrl_docurrentctrl_ReadReg(InstancePtr->Busa_BaseAddress, XCTRL_DOCURRENTCTRL_BUSA_ADDR_T_F_TB_CTRL);
    return Data & 0x1;
}

u32 XCtrl_docurrentctrl_Get_t_f_tc(XCtrl_docurrentctrl *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCtrl_docurrentctrl_ReadReg(InstancePtr->Busa_BaseAddress, XCTRL_DOCURRENTCTRL_BUSA_ADDR_T_F_TC_DATA);
    return Data;
}

u32 XCtrl_docurrentctrl_Get_t_f_tc_vld(XCtrl_docurrentctrl *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCtrl_docurrentctrl_ReadReg(InstancePtr->Busa_BaseAddress, XCTRL_DOCURRENTCTRL_BUSA_ADDR_T_F_TC_CTRL);
    return Data & 0x1;
}

u32 XCtrl_docurrentctrl_Get_t_f_ud_out(XCtrl_docurrentctrl *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCtrl_docurrentctrl_ReadReg(InstancePtr->Busa_BaseAddress, XCTRL_DOCURRENTCTRL_BUSA_ADDR_T_F_UD_OUT_DATA);
    return Data;
}

u32 XCtrl_docurrentctrl_Get_t_f_ud_out_vld(XCtrl_docurrentctrl *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCtrl_docurrentctrl_ReadReg(InstancePtr->Busa_BaseAddress, XCTRL_DOCURRENTCTRL_BUSA_ADDR_T_F_UD_OUT_CTRL);
    return Data & 0x1;
}

u32 XCtrl_docurrentctrl_Get_t_f_uq_out(XCtrl_docurrentctrl *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCtrl_docurrentctrl_ReadReg(InstancePtr->Busa_BaseAddress, XCTRL_DOCURRENTCTRL_BUSA_ADDR_T_F_UQ_OUT_DATA);
    return Data;
}

u32 XCtrl_docurrentctrl_Get_t_f_uq_out_vld(XCtrl_docurrentctrl *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCtrl_docurrentctrl_ReadReg(InstancePtr->Busa_BaseAddress, XCTRL_DOCURRENTCTRL_BUSA_ADDR_T_F_UQ_OUT_CTRL);
    return Data & 0x1;
}

void XCtrl_docurrentctrl_InterruptGlobalEnable(XCtrl_docurrentctrl *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCtrl_docurrentctrl_WriteReg(InstancePtr->Busa_BaseAddress, XCTRL_DOCURRENTCTRL_BUSA_ADDR_GIE, 1);
}

void XCtrl_docurrentctrl_InterruptGlobalDisable(XCtrl_docurrentctrl *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCtrl_docurrentctrl_WriteReg(InstancePtr->Busa_BaseAddress, XCTRL_DOCURRENTCTRL_BUSA_ADDR_GIE, 0);
}

void XCtrl_docurrentctrl_InterruptEnable(XCtrl_docurrentctrl *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XCtrl_docurrentctrl_ReadReg(InstancePtr->Busa_BaseAddress, XCTRL_DOCURRENTCTRL_BUSA_ADDR_IER);
    XCtrl_docurrentctrl_WriteReg(InstancePtr->Busa_BaseAddress, XCTRL_DOCURRENTCTRL_BUSA_ADDR_IER, Register | Mask);
}

void XCtrl_docurrentctrl_InterruptDisable(XCtrl_docurrentctrl *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XCtrl_docurrentctrl_ReadReg(InstancePtr->Busa_BaseAddress, XCTRL_DOCURRENTCTRL_BUSA_ADDR_IER);
    XCtrl_docurrentctrl_WriteReg(InstancePtr->Busa_BaseAddress, XCTRL_DOCURRENTCTRL_BUSA_ADDR_IER, Register & (~Mask));
}

void XCtrl_docurrentctrl_InterruptClear(XCtrl_docurrentctrl *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCtrl_docurrentctrl_WriteReg(InstancePtr->Busa_BaseAddress, XCTRL_DOCURRENTCTRL_BUSA_ADDR_ISR, Mask);
}

u32 XCtrl_docurrentctrl_InterruptGetEnabled(XCtrl_docurrentctrl *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCtrl_docurrentctrl_ReadReg(InstancePtr->Busa_BaseAddress, XCTRL_DOCURRENTCTRL_BUSA_ADDR_IER);
}

u32 XCtrl_docurrentctrl_InterruptGetStatus(XCtrl_docurrentctrl *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCtrl_docurrentctrl_ReadReg(InstancePtr->Busa_BaseAddress, XCTRL_DOCURRENTCTRL_BUSA_ADDR_ISR);
}

