import rtconfig
Import('RTT_ROOT')
from building import *

# get current directory
cwd = GetCurrentDir()

# The set of source files associated with this SConscript file.

src = Glob('modules/*/*.c')

path = [cwd ,cwd + '/inc']

CPPDEFINES = ['']
group = DefineGroup('MOTORFLOATLIB', src, depend = ['USER_USING_MOTORFLOATLIB'], CPPPATH = path, CPPDEFINES = CPPDEFINES)

Return('group')
