# ==============================================================
# File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
# Version: 2015.2
# Copyright (C) 2015 Xilinx Inc. All rights reserved.
# 
# ==============================================================

proc generate {drv_handle} {
    xdefine_include_file $drv_handle "xparameters.h" "XCtrl_docurrentctrl" \
        "NUM_INSTANCES" \
        "DEVICE_ID" \
        "C_S_AXI_BUSA_BASEADDR" \
        "C_S_AXI_BUSA_HIGHADDR"

    xdefine_config_file $drv_handle "xctrl_docurrentctrl_g.c" "XCtrl_docurrentctrl" \
        "DEVICE_ID" \
        "C_S_AXI_BUSA_BASEADDR"

    xdefine_canonical_xpars $drv_handle "xparameters.h" "XCtrl_docurrentctrl" \
        "DEVICE_ID" \
        "C_S_AXI_BUSA_BASEADDR" \
        "C_S_AXI_BUSA_HIGHADDR"
}

