import copy
Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd     = GetCurrentDir()
src	= Glob('*.c')

src += Glob('CTRL_doCurrentCtrl_v1_0/src/*.c')

path = [cwd ,cwd + 'CTRL_doCurrentCtrl_v1_0/src']
# remove no need file.
if GetDepend('RT_USING_LWIP') == False:
    src_need_remove = ['dm9000.c'] # need remove file list.
    SrcRemove(src, src_need_remove)

if GetDepend('RT_USING_DFS') == False:
    src_need_remove = ['sd.c'] # need remove file list.
    SrcRemove(src, src_need_remove)

CPPPATH = path

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
