import rtconfig
Import('RTT_ROOT')
from building import *

# get current directory
cwd = GetCurrentDir()

# The set of source files associated with this SConscript file.

src = Glob('UserConfig/*.c')

libs = Glob('Lib/*.a')

path = [cwd + '/inc',cwd + '/userinc']

LIBPATH = [cwd + '/Lib']

group = DefineGroup('STEMWIN', src, LIBS = libs,depend = ['RT_USING_STEMWIN'], CPPPATH = path, LIBPATH = LIBPATH)

Return('group')
